apiVersion: apps/v1
kind: Deployment
metadata:
  name: joealpine
  namespace: joe-private
  labels:
    app: joealpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joealpine
  template:
    metadata:
      labels:
        app: joealpine
    spec:
      containers:
        - name: joealpine
          image: alpine:3.16.2
          command:
            - /bin/sh
            - "-c"
            - "sleep 90d"